# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Read package version
      run: PACKAGE_VERSION=$(head -n 1 version.txt) && echo $PACKAGE_VERSION
    - name: Read changelog
      run: CHANGELOG=$(tail -n+3 version.txt) && echo $CHANGELOG
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Add execution privileges
      run: chmod +x ./gradlew
      working-directory: ./backend/burning-okr
    - name: Test
      run: ./gradlew check
      working-directory: ./backend/burning-okr
    - name: Build jar
      run: ./gradlew -PprojVersion="${PACKAGE_VERSION}" bootJar
      working-directory: ./backend/burning-okr
    - name: Build war
      run: ./gradlew -PprojVersion="${PACKAGE_VERSION}" bootWar
      working-directory: ./backend/burning-okr
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: backend/burning-okr/burning-okr-app/build/libs
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${PACKAGE_VERSION}
        release_name: Release ${PACKAGE_VERSION}
        body: ${CHANGELOG}
        draft: false
        prerelease: true

